apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: juice-shop

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: juice-shop
  app.kubernetes.io/part-of: juice-shop
  app.kubernetes.io/managed-by: kustomize

images:
  - name: bkimminich/juice-shop
    newTag: latest
